name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      id: ecr-login
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ml-app:latest

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ml-app:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

  deploy-to-ecs:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster iris-ml-cluster \
          --service iris-ml-service \
          --force-new-deployment
